
METCALCPY: "/home/Vanderlei.Vargas/Packages/METcalcpy"
METPLOTPY: "/home/Vanderlei.Vargas/Packages/METplotpy"
AGG_WFLOW: "/home/Vanderlei.Vargas/Packages/reformat/workdir/PointStat/agg_wflow"

AGG_STAT_YAML: "../config/config_agg_stat.yaml"

WORKDIR: "./workdir"

AGG_STAT: True
AGG_PREP: True

# Plots
PERFORMANCE_DIAGRAM: False
LINE: False
TAYLOR: False


