version: 2
updates:
   - package-ecosystem: "github-actions"
     directory: "/"
     schedule:
       interval: "daily"
on:
  push:
    branches: 
      - develop
      - develop-ref
      - feature_*
      - main_*
      - bugfix_*
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  documentation:
    name: Build Documentation
    runs-on: ubuntu-latest
