name: METcalcpy CI/CD Workflow
on:
  push:
    branches:
      - develop
      - develop-ref
      - feature_*
      - main_*
      - bugfix_*
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  documentation:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade python-dateutil requests sphinx \
          sphinx-gallery Pillow sphinx_rtd_theme
      - name: Build docs
        continue-on-error: true
        run: |
          DOCS_DIR=${GITHUB_WORKSPACE}/docs
          cd ${DOCS_DIR}
          make clean html
          cd ${GITHUB_WORKSPACE}
          warning_file=${DOCS_DIR}/_build/warnings.log
          mkdir -p artifact/documentation
          cp -r ${DOCS_DIR}/_build/html/* artifact/documentation
          if [ -s $warning_file ]; then
            cp -r ${DOCS_DIR}/_build/warnings.log artifact/doc_warnings.log
            cp artifact/doc_warnings.log artifact/documentation
          else
            rm ${warning_file}
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: artifact/documentation
      - uses: actions/upload-artifact@v2
        with:
          name: documentation_warnings.log
          path: artifact/doc_warnings.log
          if-no-files-found: ignore
