name: Add checksum to release

on:
  release:
    types:
      - published

jobs:
  add-checksum:
     runs-on: ubuntu-latest
     steps:
        - uses: dtcenter/metplus-action-release-checksum@test_failure
          with:
             token: ${{ secrets.METPLUS_BOT_TOKEN }}
