on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches:
      - main
      - develop
      - feature_*
      - issue_*
      - bugfix_*
      - test_*
  pull_request:
      types: [opened, synchronize, reopened]

- name: Show GitHub context   
  env: 
    GITHUB_CONTEXT: ${{ toJson(github) }}   
  run: echo "$GITHUB_CONTEXT"
  shell: bash

name: SonarQube for METcalcpy

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
#     - name: SonarQube Scan
#       uses: sonarsource/sonarqube-scan-action@master
    # Use the latest version of sonarqube scan:
    - name: Official SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v1.2.0
      with:
#          projectBaseDir: METcalcpy/metcalcpy 
          args: >
            -Dsonar.verbose=true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
