# This workflow will check for Python third-party vulnerabilities that check against the Safety DB
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python safety check

on:
  push:
    branches:
      - develop
      - develop-ref
      - feature_*
      - main_*
      - bugfix_*
      - test_*
      - issue_*
  pull_request:
    types: [opened, reopened, synchronize]


env:
  DEP_PATH: ./requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@master

      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master
        with: 
          scan_requirements_file_only: 'true'
